### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by nunojesus** [ChsHub/html_music_player#1]
Hi just want to know how can I contribute to your project and what you need?

**Comment by ChsHub** [comment]
Hi, sorry it took me so long to reply. There are some things I could need help with:
- The html/css layout of the top part can be improved. At the moment the top part is just fixed height. I wish it would adjust the height to the elements inside. Also the buttons, player, file input and volume slider don't really align with each other.
- When you jump to the next song, the track list(scroll) should focus on the next song.
- Add a way to adjust the player size, when playing a video. Maybe something like a vertical slider.
- Write a readme

Otherwise just feel free to do any improvement you can find.
